# Generated by Django 3.0.2 on 2020-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200000)),
                ('image', models.FileField(blank=True, upload_to='contact_forms')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
