# Generated by Django 3.0.2 on 2020-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirm', models.BooleanField(default=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('is_cod', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_status', models.CharField(blank=True, max_length=500)),
                ('transaction_id', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price_each', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
