# Generated by Django 3.0.2 on 2020-09-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200923_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cod',
        ),
    ]
