# Generated by Django 3.0.2 on 2020-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New Arrivals (Show on front page)'), ('R', 'Donot show on front page')], max_length=1),
        ),
    ]
