# Generated by Django 3.0.2 on 2020-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200923_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fabric',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='policy',
            new_name='disclaimer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='style',
            new_name='material',
        ),
        migrations.AddField(
            model_name='item',
            name='stretchability',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
