# Generated by Django 3.0.2 on 2020-09-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_item_is_in_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
