# Generated by Django 3.0.2 on 2020-10-04 08:45

from django.db import migrations, models
import ecommerce.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201004_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(storage=ecommerce.storage_backends.MediaStorage(), upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.FileField(blank=True, storage=ecommerce.storage_backends.MediaStorage(), upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.FileField(blank=True, storage=ecommerce.storage_backends.MediaStorage(), upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.FileField(blank=True, storage=ecommerce.storage_backends.MediaStorage(), upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.FileField(blank=True, storage=ecommerce.storage_backends.MediaStorage(), upload_to='item_images'),
        ),
    ]
